#!/bin/sh

export HILDON_DESKTOP_APPS_PRESTART=auto
export CLUTTER_BACKEND=x11
export COGL_RENDERER=egl_xlib
export COGL_DRIVER=gles2

# sadly, we have to use dsmetool here, so we cant respawn session..
/usr/sbin/dsmetool -c 3 -T 180 -m -17 -f /usr/bin/hildon-desktop
