#!/bin/sh
# This script will try to avoid randomizing the mac address of the n900
# wifi driver.

if [ "$IFACE" != wlan0 ]; then
	exit 0
fi

mac_file="/etc/network/n900-staticmac"
if ! [ -f "$mac_file" ]; then
	macaddr="$(ip a show dev wlan0 | awk '/link\/ether/ {print $2}')"
	echo "macaddr=$macaddr" > "$mac_file"
fi

. "$mac_file"

ip link set dev $IFACE address "$macaddr"
